name: Validate Backstage plugins

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Tests
        run: make test

      - name: Build plugins
        run: make build
