name: Publish Backstage plugins to npm

on:
  push:
    branches:
      - main

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@scott-the-programmer'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Tests
        run: make test

      - name: Build plugins
        run: make build

      - name: Publish frontend
        run: |
          make build-frontend
          cd spacelift
          yarn publish --access public || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish backend
        run: |
          make build-backend
          cd spacelift-backend
          yarn publish --access public || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
